project_id = "wfyisqyqlijmaifunhqv"

[functions.get-api-keys]
verify_jwt = false

[functions.get-fixtures]
verify_jwt = false

[functions.get-basketball]
verify_jwt = false

[functions.get-boxing]
verify_jwt = false

[functions.get-streams]
verify_jwt = false
